spring:
  datasource:
    url: jdbc:postgresql://ep-late-firefly-ahilmwdj-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_DvLsC7rB9geu

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

sms:
  provider: msg91
  auth:
    key: YOUR_MSG91_AUTH_KEY
  template:
    id: YOUR_TEMPLATE_ID
  sender: CSDAPP